name: Installation Instruction Action
description: Installs from a config file to your github action runner.
branding:
  icon: arrow-down-circle
  color: orange
inputs:
  path:
    description: Path to directory, file or a remote git repository url containing the config file.
    required: true
    type: string
  options:
    description: Options as string to pass to ibi cli. (Please check locally if it works.)
    type: string
  version:
    description: Version of installation-instruction to use. If empty, uses the latest version.
    type: string

runs:
  using: composite
  steps:
    - name: Install Python
      uses: actions/setup-python@v5
      id: cp312
      with:
        python-version: 3.12
        update-environment: false
    - name: Install Installation Instruction (latest)
      if: ${{ inputs.version == '' }}
      shell: pwsh
      run: ${{ steps.cp312.outputs.python-path }} -m pip install installation-instruction
    - name: Install Installation Instruction (with version)
      if: ${{ inputs.version != '' }}
      shell: pwsh
      run: ${{ steps.cp312.outputs.python-path }} -m pip install 'installation-instruction==${{ inputs.version }}'
    - name: Install from Config File
      shell: pwsh
      run: ${{ steps.cp312.outputs.python-path }} -m installation_instruction install ${{ inputs.path }} ${{ inputs.options }}
      
  