name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Test Github Action
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Test Install
        uses: ./action.yaml
        with:
          path: ./tests/
          options: --something
      - name: Assert Output
        shell: pwsh
        run: if ( !( (get-content ./cool.sh) -match "echo something" ) ) { exit 1 }

  test2:
    name: Test Github Action 2
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Test Install
        uses: ./action.yaml
        with:
          path: ./tests/
          version: 0.4.0
      - name: Assert Output
        shell: pwsh
        run: if ( !( (get-content ./cool.sh) -match "echo nothing" ) ) { exit 1 }